spring:
  application:
      name: base-framwork
  profiles:
      active: dev

# apollo配置
app:
  id: base-framwork # Apollo管理平台中创建的项目的ID
apollo:
  meta: http://1.15.47.109:8080 # ConfigService访问地址
  bootstrap:
    enabled: true # 开启Apollo
    namespaces: application,threadpool

logging:
  level:
    com: info


server:
  port: 8080
