server:
  port: 8088
spring:
  application:
    name: base-framwork

# apollo配置
app:
  id: base-framwork # Apollo管理平台中创建的项目的ID
apollo:
  meta: http://1.15.47.109:8080 # ConfigService访问地址
  cacheDir: D:/cacheDir # 定义缓存目录，Apollo会自动缓存配置到当前目录中
  bootstrap:
    enabled: true # 开启Apollo

logging:
  level:
    com: info