spring:
  application:
    name: chuyx-framwork
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://1.15.47.109:3306/base?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080
mybatis-plus:
  type-aliases-package: com.chuyx.pojo.*
  mapper-locations: classpath:**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl