# 启动端口
server:
  port: 8080

# mp配置
mybatis-plus:
  type-aliases-package: com.chuyx.pojo.*
  mapper-locations: classpath:mybatis/mapper/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出方式

# mq配置
spring:
  rabbitmq:
    username: guest
    password: guest
    host: 1.15.47.109
    port: 5672
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledge-mode: manual